In [12]:
import numpy as np

print("=== 1. ИМПОРТ БИБЛИОТЕКИ ===")
# Импортируем NumPy с общепринятым сокращением
print("Импортировал NumPy!")

=== 1. ИМПОРТ БИБЛИОТЕКИ ===
Импортировал NumPy!


In [ ]:
print("\n=== 2. СОЗДАНИЕ МАССИВОВ ===")

# Создание массива из обычного списка Python
list = [1, 2, 3, 4, 5]
arraylist = np.array(list)
print("Массив из списка:", arraylist)

# Создание двумерного массива из вложенных списков
matrix_from_list = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Двумерный массив из списков:):")
print(matrix_from_list)

# Создание массива нулей
zeros_array = np.zeros((3, 4))
print("\nМассив нулей 3x4:")
print(zeros_array)

# Создание массива единиц
ones_array = np.ones((2, 3))
print("Массив единиц 2x3:")
print(ones_array)

# Создание массива с последовательностью чисел
range_array = np.arange(0, 10, 2)  # от 0 до 10 с шагом 2
print("Массив от 0 до 10 с шагом 2:", range_array)

# Создание массива со случайными значениями
random_array = np.random.rand(2, 3)
print("Массив случайных значений 2x3:")
print(random_array)


=== 2. СОЗДАНИЕ МАССИВОВ ===
Массив из списка: [1 2 3 4 5]
Двумерный массив из списков:):
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Массив нулей 3x4:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Массив единиц 2x3:
[[1. 1. 1.]
 [1. 1. 1.]]
Массив от 0 до 10 с шагом 2: [0 2 4 6 8]
Массив случайных значений 2x3:
[[0.77537326 0.89781992 0.08750316]
 [0.74200447 0.13410398 0.69857979]]


In [9]:
print("\n=== 3. АТРИБУТЫ МАССИВОВ ===")

# Атрибуты shape и dtype
demo_array = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float64)
print("Демонстрационный массив:")
print(demo_array)
print("Форма массива (shape):", demo_array.shape)  # Размерность массива
print("Тип данных (dtype):", demo_array.dtype)    # Тип элементов массива
print("Количество элементов:", demo_array.size)   # Общее количество элементов
print("Размерность:", demo_array.ndim, "мерный")  # Количество измерений


=== 3. АТРИБУТЫ МАССИВОВ ===
Демонстрационный массив:
[[1. 2. 3.]
 [4. 5. 6.]]
Форма массива (shape): (2, 3)
Тип данных (dtype): float64
Количество элементов: 6
Размерность: 2 мерный


In [5]:
print("\n=== 4. ИНДЕКСИРОВАНИЕ И СРЕЗЫ ===")

# Создаем массив для демонстрации индексирования
index_array = np.array([[10, 20, 30, 40], 
                       [50, 60, 70, 80], 
                       [90, 100, 110, 120]])
print("Исходный массив 3x4:")
print(index_array)

# Получение отдельного элемента
element = index_array[1, 2]  # Строка 1, столбец 2 (индексация с 0)
print(f"Элемент [1, 2]: {element}")

# Извлечение подмассива с помощью срезов
# Синтаксис: [начало:конец:шаг]
row_slice = index_array[0, :]  # Первая строка, все столбцы
print("Первая строка:", row_slice)

column_slice = index_array[:, 1]  # Все строки, второй столбец
print("Второй столбец:", column_slice)

sub_array = index_array[0:2, 1:3]  # Строки 0-1, столбцы 1-2
print("Подмассив [0:2, 1:3]:")
print(sub_array)

# Срез с шагом
stepped_slice = index_array[::2, ::2]  # Каждая вторая строка и столбец
print("Срез с шагом 2:")
print(stepped_slice)


=== 4. ИНДЕКСИРОВАНИЕ И СРЕЗЫ ===
Исходный массив 3x4:
[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]
Элемент [1, 2]: 70
Первая строка: [10 20 30 40]
Второй столбец: [ 20  60 100]
Подмассив [0:2, 1:3]:
[[20 30]
 [60 70]]
Срез с шагом 2:
[[ 10  30]
 [ 90 110]]
