In [48]:
import numpy as np

print("=== 1. ИМПОРТ БИБЛИОТЕКИ ===")
# Импортируем NumPy с общепринятым сокращением

=== 1. ИМПОРТ БИБЛИОТЕКИ ===


In [49]:
print("\n=== 2. СОЗДАНИЕ МАССИВОВ ===")
print("2.1")
# Создаю массив из обычного списка Python
list = [1, 2, 3, 4, 5]
arraylist = np.array(list)
print("Массив из списка:", arraylist)


=== 2. СОЗДАНИЕ МАССИВОВ ===
2.1
Массив из списка: [1 2 3 4 5]


In [50]:
print(2.2)
# Создаю двумерный массив из вложенных списков
matrixlist = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Двумерный массив из списков:")
print(matrixlist)


2.2
Двумерный массив из списков:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [51]:
print("2.3")
# Создаю массив нулей
zeros_array = np.zeros((3, 4))
print("\nМассив нулей 3x4:")
print(zeros_array)

2.3

Массив нулей 3x4:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [52]:
print("2.4")
# Созданю массив единиц
ones_array = np.ones((2, 3))
print("Массив единиц 2x3:")
print(ones_array)

2.4
Массив единиц 2x3:
[[1. 1. 1.]
 [1. 1. 1.]]


In [53]:
print("2.5")
# Создаю массив с последовательностью чисел
rangearray = np.arange(0, 10, 2)  
print("Массив от 0 до 10 с шагом 2:", rangearray)

2.5
Массив от 0 до 10 с шагом 2: [0 2 4 6 8]


In [54]:
print("2.6")
# Создаю массив со случайными значениями
randarray = np.random.rand(2, 3)
print("Массив случайных значений 2x3:")
print(randarray)

2.6
Массив случайных значений 2x3:
[[0.61990094 0.87114384 0.37079461]
 [0.26876927 0.44399789 0.44732941]]


In [55]:
print("\n=== 3. АТРИБУТЫ МАССИВОВ :_)===")

# Демонстрирую вам  атрибуты shape и dtype :)
demKaarray = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float64)
print("Демонстрационный массив:")
print(demKaarray)
print("Форма массива (shape):", demKaarray.shape)  # Размерность массива
print("Тип данных (dtype):", demKaarray.dtype)    # Тип элементов массива
print("Количество элементов:", demKaarray.size)   # Общее количество элементов
print("Размерность:", demKaarray.ndim, "мерный")  # Количество измерений


=== 3. АТРИБУТЫ МАССИВОВ :_)===
Демонстрационный массив:
[[1. 2. 3.]
 [4. 5. 6.]]
Форма массива (shape): (2, 3)
Тип данных (dtype): float64
Количество элементов: 6
Размерность: 2 мерный


In [56]:
print("\n=== 4. ИНДЕКСИРОВАНИЕ И СРЕЗЫы ===")
print("4.1")
# Создаем массив для демонстрации индексирования
indexarray = np.array([[10, 20, 30, 40], 
                       [50, 60, 70, 80], 
                       [90, 100, 110, 120]])
print("Исходный массив 3x4:")
print(indexarray)



=== 4. ИНДЕКСИРОВАНИЕ И СРЕЗЫы ===
4.1
Исходный массив 3x4:
[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]


In [57]:
print("4.2")
# Получаю отдельный элемент
element = indexarray[1, 2]  # Строка 1, столбец 2 (индексация с 0)
print(f"Элемент [1, 2]: {element}")

4.2
Элемент [1, 2]: 70


In [58]:
print("4.3")
# Извлекаю подмассив с помощью срезов
rowsl = index_array[0, :]  
print("Первая строка:", rowsl)

4.3
Первая строка: [10 20 30 40]


In [59]:
print("4.4")
column_slice = index_array[:, 1]  # пупупу пупу
print("Второй столбец:", column_slice)

4.4
Второй столбец: [ 20  60 100]


In [60]:
print("4.5")
subAarray = index_array[0:2, 1:3]  # Строки 0-1, столбцы 1-2
print("Подмассив [0:2, 1:3]:")
print(subAarray)



4.5
Подмассив [0:2, 1:3]:
[[20 30]
 [60 70]]


In [61]:
print("4.6")
# Срез с шагом
steppedsl = index_array[::2, ::2]  # Каждая вторая строка и столбец
print("Срез с шагом 2:")
print(steppedsl)

4.6
Срез с шагом 2:
[[ 10  30]
 [ 90 110]]


In [62]:
print("\n=== 5. ВЕКТОРНЫЕ ОПЕРАЦИИ И СТАТИСТИКА ===")

# Создаем два массива для операций
array_a = np.array([1, 2, 3, 4, 5])
array_b = np.array([10, 20, 30, 40, 50])

print("Массив A:", array_a)
print("Массив B:", array_b)

# Поэлементное сложение массивов
addition = array_a + array_b
print("Поэлементное сложение A + B:", addition)

# Поэлементное умножение массивов
multiplication = array_a * array_b
print("Поэлементное умножение A * B:", multiplication)

# Математические операции с массивами
squared = array_a ** 2
print("Квадрат элементов массива A:", squared)

# Базовые статистические операции
print("\n--- СТАТИСТИЧЕСКИЕ ХАРАКТЕРИСТИКИ ---")
print("Массив для статистики:", array_a)

mean_value = np.mean(array_a)  # Среднее значение
print("Среднее значение:", mean_value)

sum_value = np.sum(array_a)    # Сумма всех элементов
print("Сумма всех элементов:", sum_value)

max_value = np.max(array_a)    # Максимальное значение
print("Максимальный элемент:", max_value)

min_value = np.min(array_a)    # Минимальное значение
print("Минимальный элемент:", min_value)

std_value = np.std(array_a)    # Стандартное отклонение
print("Стандартное отклонение:", std_value)

# Статистика для двумерного массива pypy
matrix_stats = np.random.rand(4, 3)
print("\nДвумерный массив для статистики:")
print(matrix_stats)
print("Среднее по всему массиву:", np.mean(matrix_stats))
print("Среднее по столбцам:", np.mean(matrix_stats, axis=0))
print("Среднее по строкам:", np.mean(matrix_stats, axis=1))


=== 5. ВЕКТОРНЫЕ ОПЕРАЦИИ И СТАТИСТИКА ===
Массив A: [1 2 3 4 5]
Массив B: [10 20 30 40 50]
Поэлементное сложение A + B: [11 22 33 44 55]
Поэлементное умножение A * B: [ 10  40  90 160 250]
Квадрат элементов массива A: [ 1  4  9 16 25]

--- СТАТИСТИЧЕСКИЕ ХАРАКТЕРИСТИКИ ---
Массив для статистики: [1 2 3 4 5]
Среднее значение: 3.0
Сумма всех элементов: 15
Максимальный элемент: 5
Минимальный элемент: 1
Стандартное отклонение: 1.4142135623730951

Двумерный массив для статистики:
[[0.12348227 0.5616411  0.0563798 ]
 [0.34336894 0.55889239 0.91985541]
 [0.09083737 0.20266153 0.25358792]
 [0.78163631 0.4674675  0.60910967]]
Среднее по всему массиву: 0.4140766840043604
Среднее по столбцам: [0.33483122 0.44766563 0.4597332 ]
Среднее по строкам: [0.24716772 0.60737225 0.18236227 0.61940449]
